name: cvms-ucvm-ci

on:
  push:
    branches: [ main ]

jobs:
  cvms-build-ucvm-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvms/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvms/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: testMei 
        path: ucvm
    - name: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvms'
         target-model: 'cvms'
         target-branch: 'testMei'
    - name: get-result
      run: more ${{ steps.build-ucvm-action.outputs.build-log }}
      shell: bash
    - name: move stock cvms away
      run: (rm -rf $RUNNER_WORKSPACE/cvms/ucvm/work/model/cvms)
      shell: bash
### build cvms from github 
    - name: checkout cvms main 
      uses: actions/checkout@v2
      with: 
        ref: main
        path: cvms
    - name: move it to the right location
      run: (mv cvms $RUNNER_WORKSPACE/cvms/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvms as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvms/ucvm/work/model/cvms; ./.github/scripts/cvms-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvms with ucvm
      run: (cd $RUNNER_WORKSPACE/cvms/ucvm/work/model/cvms; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvms-test-ucvm.sh)
      shell: bash
    - name: test cvms under ucvm
      run: (cd $RUNNER_WORKSPACE/cvms/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash

  cvms-build-ucvm-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/cvms/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/cvms/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - id: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
        ref: testMei 
        path: ucvm
    - name: build-ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'cvms'
         target-model: 'cvms'
         target-branch: 'testMei'
    - name: Start SSH debug with tmate
      if: ${{ success() }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
    - name: sleep to keep runner alive
      run: sleep 3600
    - name: get-result
      run: more ${{ steps.build-ucvm-action.outputs.build-log }}
      shell: bash
    - name: move stock cvms away
      run: (rm -rf $RUNNER_WORKSPACE/cvms/ucvm/work/model/cvms)
      shell: bash
### build cvms from github 
    - name: checkout cvms main 
      uses: actions/checkout@v2
      with: 
        ref: main
        path: cvms
    - name: move it to the right location
      run: (mv cvms $RUNNER_WORKSPACE/cvms/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build cvms as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/cvms/ucvm/work/model/cvms; ./.github/scripts/cvms-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test cvms with ucvm
      run: (cd $RUNNER_WORKSPACE/cvms/ucvm/work/model/cvms; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/cvms-test-ucvm.sh)
      shell: bash
    - name: test cvms under ucvm
      run: (cd $RUNNER_WORKSPACE/cvms/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash
